### ISSUE TITLE
after a division / there is only comment

### ISSUE THREAD

**Issue by mesopelagique** [ayoubserti/lang-4d#11]
```4dm
$test:=1 // a number
$div:=2/1  
$other:="a string" // a string
```

see when creating https://github.com/mesopelagique/learnxinyminutes-docs/blob/feature/4d/4d.html.markdown

**Comment by ayoubserti** [comment]
fixed directly on main.

**Comment by mesopelagique** [comment]
you can link the fix https://github.com/ayoubserti/lang-4d-support/commit/f30975193df58b3a4f2b473f60d898d6722111ea

how it is released on github? (so when we can see github coloration fixed)

do you prefer issues on lang-4d-support?

**Comment by ayoubserti** [comment]
Github colorization depends on this repo. Basically, github-linguist release a version every 1-2 months. Then, I expect a new release by the beginning of March.

I prefer issues here.  `lang-4d-support` is intended to be for IntelliSense and much more.
